---
  version: "3.0"
  services:
    # Database
    db:
      image: postgres:12.0-alpine
      ports:
        - ${OPOLY_DB_PORT}:5432
      environment:
        OPOLY_ENV: ${OPOLY_ENV}
        POSTGRES_USER: ${OPOLY_DB_USER}
        POSTGRES_DATABASE: ${OPOLY_DB_NAME}
        POSTGRES_PASSWORD: ${OPOLY_DB_PASS}
      volumes:
        - ./.data/db:/var/lib/postgresql/data
      restart: on-failure

    # Server
    api:
      build: server
      depends_on:
        - db
      ports:
        - ${OPOLY_SERVER_PORT}:5000
      working_dir: /server
      command: "nodemon ."
      environment:
        OPOLY_ENV: ${OPOLY_ENV}
        OPOLY_DB_PORT: ${OPOLY_DB_PORT}
        OPOLY_DB_USER: ${OPOLY_DB_USER}
        OPOLY_DB_NAME: ${OPOLY_DB_NAME}
        OPOLY_DB_PASS: ${OPOLY_DB_PASS}
        OPOLY_SERVER_PORT: ${OPOLY_SERVER_PORT}
      volumes:
        - ./server:/server

    # Client
    client:
      image: nginx:1.17.4-alpine
      depends_on:
        - api
      ports:
        - ${OPOLY_CLIENT_PORT}:80
      environment:
        OPOLY_ENV: ${OPOLY_ENV}
        OPOLY_SERVER_PORT: ${OPOLY_SERVER_PORT}
      volumes:
        - ./client/build:/client
        - ./configuration/web.conf:/etc/nginx/conf.d/default.conf
        - ./configuration/errorpages:/usr/share/nginx/html/errorpages
  